project_name: codex
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/codex/main.go
    binary: codex
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}" # For reproducible builds
    ldflags:
      - -s -w
      - -X github.com/khulnasoft/codex/internal/build.Version={{.Version}}
      - -X github.com/khulnasoft/codex/internal/build.Commit={{.Commit}}
      - -X github.com/khulnasoft/codex/internal/build.CommitDate={{.CommitDate}}
      - -X github.com/khulnasoft/codex/internal/build.SentryDSN={{ .Env.SENTRY_DSN }}
      - -X github.com/khulnasoft/codex/internal/build.TelemetryKey={{ .Env.TELEMETRY_KEY }}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
      - arm
    goarm:
      - 7
archives:
  - files:
      - no-files-will-match-* # Glob that does not match to create archive with only binaries.
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if eq .Arch "arm" }}v{{ .Arm }}l{{ end }}'
snapshot:
  name_template: "{{ .Env.EDGE_TAG }}"
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
release:
  prerelease: auto
  draft: true
  github:
    owner: khulnasoft
    name: codex
announce:
  discord:
    # Whether its enabled or not.
    # Defaults to false.
    enabled: false

    # Message template to use while publishing.
    # Defaults to `{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}`
    message_template: |
      **New Release: Codex {{.Tag}}**
      We just released a version {{.Tag}} of `codex`.

      Description:
      {{.TagBody}}

      Release: {{.ReleaseURL}}

      Updating:
      If you installed codex via our recommended installer
      (`curl -fsSL https://get.khulnasoft.com/codex | bash`) you will get the new version
      _automatically_, the next time you run `codex`

      Thanks,
      khulnasoft.com

    # Set author of the embed.
    # Defaults to `GoReleaser`
    author: "khulnasoft.com"

    # Color code of the embed. You have to use decimal numeral system, not hexadecimal.
    # Defaults to `3888754` - the grey-ish from goreleaser
    color: "2622553" #This is the Khulnasoft Space color

    # URL to an image to use as the icon for the embed.
    # Defaults to `https://goreleaser.com/static/avatar.png`
    icon_url: ""
